spring:
  datasource:
    url: jdbc:postgresql://localhost:5932/testproject
    username: testproject
    password: T35t!
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
server:
  port: 8080

jwt:
  secret: projsecret